[package]
name = "xorword"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
plotly = "0.6.0"
just = "1.14.0"
str-distance = "0.1.0"
